name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: 1.0.3
  material_color_generator: 1.1.0
  palette_generator: 0.3.3+3
  provider: 6.0.3
  shared_preferences: ^2.0.0
  flutter_limited_checkbox: ^0.0.1
assets:
  -images/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
