

class AppLocalization {
  static String currentLanguage = 'en'; // Default language

  static String getTranslatedValue(String key) {
    // Map your keys to localized strings for each language
    Map<String, Map<String, String>> localizedStrings = {
      'en': {
        "Strona Główna" "Heim" "Дом" : 'Main Page',
        "Ustawienia" "Einstellungen" "Настройки" : 'Settings',
        "Menadżer Zadań" "Taskmanager" "Диспетчер Эадач" : 'Task Manager',
        "System Liczb" "Zahlensysteme" "Системы Счисления" : 'Number Systems',
        "Przelicznik jednostek" "Einheitenumwandler" "Конвертер" : 'Unit Conventer',
        "Kalkulator Kalorii" "Kalorienrechner" "Калькулятор Калорий" : 'Calorie Calculator',
        "Kalkulator Prawdopodobieństwa" "Wahrscheinlichkeitsrechner" "Калькулятор Вероятности" : 'Propability Calculator',
        "Logowanie" "Anmeldung" "Авторизоваться" : 'Log in',
        "Nazwa użytkownika" "Nutzername" "Имя Пользователя" : 'Username',
        "Hasło" "Passwort" "Пароль" : 'Password',
        "Zaloguj" "Anmeldung" "Авторизоваться" : 'Login',
        "Motyw" "Thema" "Тема" : 'Theme',
        "Język" "Zunge" "Язык" : 'Language',
        "Zastosuj" "Anwenden" "Применять" : 'Apply',
        "Nazwa" "Name" "Имя" : 'Name',
        "Dodaj" "Hinzufügen" "Добавлять" : 'Add',
        "Wszystkie Kalorie" "Alle Kalorien" "Все Калории" : 'All Calories',
        "System Binarny" "Binärsystem" "Бинарная Система " : 'Binary System',
        "System Ósemkowy" "Oktalsystem" "Восьмеричная Cистема" : 'Octal System',
        "System Decymalny" "Dezimalsystem" "Десятичная Cистема" : 'Decimal System',
        "System Szesnastkowy" "Hexadezimalsystem" "Шестнадцатеричная Cистема" : 'Hexadecimal System',
        "System Dwudziestkowy" "Basis-20-System" "Двадцатеричная Cистема" : 'Base-20 System',
        "Liczba korzystnych zdarzeń" "Anzahl der günstigen Ereignisse" "Количество Благоприятных Исходов" : 'Number of Favorable Outcomes',
        "Liczba wszystkich możliwych zdarzeń" "Gesamtzahl der möglichen Ereignisse" "Общее количество возможных исходов" : 'Total Number of Possible Outcomes',
        "Oblicz" "Berechnen" "Рассчитать" : 'Calculate',
        "Wynik:" "Ergebnis:" "Результат:" : 'Result:',
      },
      'pl': {
        "Main Page" "Heim" "Дом" : 'Strona Główna',
        "Settings" "Einstellungen" "Настройки" : 'Ustawienia',
        "Task Manager" "Taskmanager" "Диспетчер Эадач" : 'Menadżer Zadań',
        "Number Systems" "Zahlensysteme" "Системы Счисления" : 'System Liczb',
        "Unit Conventer" "Einheitenumwandler" "Конвертер" : 'Przelicznik jednostek',
        "Calorie Calculator" "Kalorienrechner" "Калькулятор Калорий" : 'Kalkulator Kalorii',
        "Propability Calculator" "Wahrscheinlichkeitsrechner" "Калькулятор Вероятности" : 'Kalkulator Prawdopodobieństwa',
        "Log in" "Anmeldung" "Авторизоваться" : 'Logowanie',
        "Username" "Nutzername" "Имя Пользователя" : 'Nazwa użytkownika',
        "Password" "Passwort" "Пароль" : 'Hasło',
        "Login" "Anmeldung" "Авторизоваться" : 'Zaloguj',
        "Theme" "Thema" "Тема" : 'Motyw',
        "Language" "Zunge" "Язык" : 'Język',
        "Apply" "Anwenden" "Применять" : 'Zastosuj',
        "Name" "Name" "Имя" : 'Nazwa',
        "Add" "Hinzufügen" "Добавлять" : 'Dodaj',
        "All Calories" "Alle Kalorien" "Все Калории" : 'Wszystkie Kalorie',
        "Binary System" "Binärsystem" "Бинарная Система " : 'System Binarny',
        "Octal System" "Oktalsystem" "Восьмеричная Cистема" : 'System Ósemkowy',
        "Decimal System" "Dezimalsystem" "Десятичная Cистема" : 'System Decymalny' ,
        "Hexadecimal System" "Hexadezimalsystem" "Шестнадцатеричная Cистема" : 'System Szesnastkowy',
        "Base-20 System" "Basis-20-System" "Двадцатеричная Cистема" : 'System Dwudziestkowy',
        "Number of Favorable Outcomes" "Anzahl der günstigen Ereignisse" "Количество Благоприятных Исходов" : 'Liczba korzystnych zdarzeń',
        "Total Number of Possible Outcomes" "Gesamtzahl der möglichen Ereignisse" "Общее количество возможных исходов" : 'Liczba wszystkich możliwych zdarzeń',
        "Calculate" "Berechnen" "Рассчитать" : 'Oblicz',
        "Result:" "Ergebnis:" "Результат:" : 'Wynik:',
      },
      'de': {
        "Main Page" "Strona Główna" "Дом" : 'Heim',
        "Settings" "Ustawienia" "Настройки" : 'Einstellungen',
        "Task Manager" "Menadżer Zadań" "Диспетчер Эадач" : 'Taskmanager',
        "Number Systems" "System Liczb" "Системы Счисления" : 'Zahlensysteme',
        "Unit Conventer" "Przelicznik jednostek" "Конвертер" : 'Einheitenumwandler',
        "Calorie Calculator" "Kalkulator Kalorii" "Калькулятор Калорий" : 'Kalorienrechner',
        "Propability Calculator" "Kalkulator Prawdopodobieństwa" "Калькулятор Вероятности" : 'Wahrscheinlichkeitsrechner',
        "Log in" "Logowanie" "Авторизоваться" : 'Anmeldung',
        "Username" "Nazwa użytkownika" "Имя Пользователя" : 'Nutzername',
        "Password" "Hasło" "Пароль" : 'Passwort',
        "Login" "Zaloguj" "Авторизоваться" : 'Anmeldung',
        "Theme" "Motyw" "Тема" : 'Thema',
        "Language" "Język" "Язык" : 'Zunge',
        "Apply" "Zastosuj" "Применять" : 'Anwenden',
        "Name" "Nazwa" "Имя" : 'Name',
        "Add" "Dodaj" "Добавлять" : 'Hinzufügen',
        "All Calories" "Wszystkie Kalorie" "Все Калории" : 'Alle Kalorien',
        "Binary System" "System Binarny" "Бинарная Система " : 'Binärsystem',
        "Octal System" "System Ósemkowy" "Восьмеричная Cистема" : 'Oktalsystem',
        "Decimal System" "System Decymalny" "Десятичная Cистема" : 'Dezimalsystem',
        "Hexadecimal System" "System Szesnastkowy" "Шестнадцатеричная Cистема" : 'Hexadezimalsystem',
        "Base-20 System" "System Dwudziestkowy" "Двадцатеричная Cистема" : 'Basis-20-System',
        "Number of Favorable Outcomes" "Liczba korzystnych zdarzeń" "Количество Благоприятных Исходов" : 'Anzahl der günstigen Ereignisse',
        "Total Number of Possible Outcomes" "Liczba wszystkich możliwych zdarzeń" "Общее количество возможных исходов" : 'Gesamtzahl der möglichen Ereignisse',
        "Calculate" "Oblicz" "Рассчитать" : 'Berechnen',
        "Result:" "Wynik:" "Результат:" : 'Ergebnis:',
      },
      'ru' : {
        "Main Page" "Heim" "Strona Główna" : 'Дом',
        "Settings" "Einstellungen" "Ustawienia" : 'Настройки',
        "Task Manager" "Taskmanager" "Menadżer Zadań" : 'Диспетчер Эадач',
        "Number Systems" "Zahlensysteme" "System Liczb" : 'Системы Счисления',
        "Unit Conventer" "Einheitenumwandler" "Przelicznik jednostek" : 'Конвертер',
        "Calorie Calculator" "Kalorienrechner" "Kalkulator Kalorii" : 'Калькулятор Калорий',
        "Propability Calculator" "Wahrscheinlichkeitsrechner" "Kalkulator Prawdopodobieństwa" : 'Калькулятор Вероятности',
        "Log in" "Anmeldung" "Logowanie" : 'Авторизоваться',
        "Username" "Nutzername" "Nazwa użytkownika" : 'Имя Пользователя',
        "Password" "Passwort" "Hasło" : 'Пароль',
        "Login" "Anmeldung" "Zaloguj" : 'Авторизоваться',
        "Theme" "Thema" "Motyw" : 'Тема',
        "Language" "Zunge" "Język" : 'Язык',
        "Apply" "Anwenden" "Zastosuj" : 'Применять',
        "Name" "Name" "Nazwa" : 'Имя',
        "Add" "Hinzufügen" "Dodaj" : 'Добавлять',
        "All Calories" "Alle Kalorien" "Wszystkie Kalorie" : 'Все Калории',
        "Binary System" "Binärsystem" "System Binarny" : 'Бинарная Система',
        "Octal System" "Oktalsystem" "System Ósemkowy" : 'Восьмеричная Cистема',
        "Decimal System" "Dezimalsystem" "System Decymalny" : 'Десятичная Cистема' ,
        "Hexadecimal System" "Hexadezimalsystem" "System Szesnastkowy" : 'Шестнадцатеричная Cистема',
        "Base-20 System" "Basis-20-System" "System Dwudziestkowy" : 'Двадцатеричная Cистема',
        "Number of Favorable Outcomes" "Anzahl der günstigen Ereignisse" "Liczba korzystnych zdarzeń" : 'Количество Благоприятных Исходов',
        "Total Number of Possible Outcomes" "Gesamtzahl der möglichen Ereignisse" "Liczba wszystkich możliwych zdarzeń" : 'Общее количество возможных исходов',
        "Calculate" "Berechnen" "Oblicz" : 'Рассчитать',
        "Result:" "Ergebnis:" "Wynik:" : 'Результат:',
      }
    };

    // Return the translated value for the given key
    return localizedStrings[currentLanguage]?[key] ?? key;
  }

  static void changeLanguage(String languageCode) {
    // Change the current language
    currentLanguage = languageCode;
  }
}